---
abstract: 'Convert (La)TeX formulas to ASCII art'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-AsciiTeX
provides:
  Text::AsciiTeX:
    file: lib/Text/AsciiTeX.pm
    version: 0.01
requires:
  parent: 0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
